name: Auto Pull Request

on:
  push:
    branches:
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.token }}
          branch: dev
          base: master
          title: Automated Pull Request
          commit-message: this is a test commit
          body: >
            This pull request was automatically created by the CI/CD pipeline.
