name: Auto Pull Request

on:
  push:
    branches:
      - mehreen

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request 
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "mehreen"
          base: master
          title: "Automated Pull Request"
          committer: "${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          author: "${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          body: |
            This pull request was automatically created by the CI/CD pipeline.
        token: ${{ secrets.token }}
