name: Auto Pull Request

on:
  push:
    branches:
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.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}}
          branch: dev
          base: master
          title: Automated Pull Request
          body: |
            This pull request was automatically created by the CI/CD pipeline.
